name = "BootstrapVirasoro"
uuid = "ca6c609c-7c6b-4ea6-be06-ee6e3ced7d6c"
authors = ["Paul_Roux"]
version = "0.0.2"

[deps]
BarnesDoubleGamma = "8c4ec0a7-3a81-41b6-9d5f-01f75984e8d3"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
EllipticFunctions = "6a4e32cb-b31a-4929-85af-fb29d9a80738"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MutableArithmetics = "d8a4904e-b15c-11e9-3269-09a3773c0cb0"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
BarnesDoubleGamma = "1"
CSV = "0"
DataFrames = "1"
EllipticFunctions = "2"
LaTeXStrings = "1"
LinearAlgebra = "1"
MutableArithmetics = "1"
PrettyTables = "2"
Printf = "1"
Random = "1"
SpecialFunctions = "2"
julia = "1.6"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[targets]
test = ["BenchmarkTools"]
