name = "BootstrapVirasoro"
uuid = "ca6c609c-7c6b-4ea6-be06-ee6e3ced7d6c"
version = "0.2.0"
authors = ["Paul_Roux"]

[deps]
Arblib = "fb37089c-8514-4489-9461-98f9c8763369"
BarnesDoubleGamma = "8c4ec0a7-3a81-41b6-9d5f-01f75984e8d3"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"

[compat]
Arblib = "1"
BarnesDoubleGamma = "1.2.5"
LaTeXStrings = "1"
PrettyTables = "2"
julia = "1.6"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[targets]
test = ["BenchmarkTools"]
